spring:
  datasource:
    url: jdbc:mysql://localhost:23306/hotspring_db
    username: admin
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  configuration:
    map-underscore-to-camel-case: true