spring:
  datasource:
    url: jdbc:mysql://localhost:23306/hotspring_db
    username: admin
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  messages:
    basename: messages
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
aws:
  s3:
    endpoint-url: http://localhost:4566
    bucket: hotspring
    key-pattern: image/{0};
  cognito:
    user-pool-id: default #構成で設定すること
    client-id: default #構成で設定すること