version: "3.8"
services:
  db:
    image: mysql:8.0
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "23306:3306"
    environment:
      MYSQL_DATABASE: hotspring_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      TZ: "Asia/Tokyo"
  localstack:
    image: localstack/localstack:latest
    environment:
      - DEFAULT_REGION=ap-northeast-1
      - DATA_DIR=/var/lib/localstack/data
    volumes:
      - ./localstack:/var/lib/localstack
    ports:
      - 4566:4566