version: "3.8"
services:
  db:
    image: mysql:8.0
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "23306:3306"
    environment:
      MYSQL_DATABASE: hotspring_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      TZ: "Asia/Tokyo"